config/routes.rb
Rails.application.routes.draw do
  resources :owners
  # resources :dogs, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  resources :dogs

  root 'dogs#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  belongs_to :owner
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  def index
    @dogs = Dog.all
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)

    if @dog.save
      redirect_to dogs_url, notice: "Successfully Saved"
    else
      flash.now[:notice] = "Something went wrong and we couldn't save your dog."
      render :new
    end
  end

  def show
    @dog = Dog.find(params[:id])
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])

    if @dog.update(dog_params)
      redirect_to dogs_url, notice: "Successfully updated #{@dog.name}."
    else
      flash.now[:notice] = "Something went wrong. We couldn't update #{@dog.name}"
      render :edit
    end
  end

  def destroy
    @dog = Dog.find(params[:id])

    if @dog.destroy
      redirect_to dogs_url, notice: "Successfully deleted #{@dog.name}."
    else
      redirect_to dogs_url, notice: "Couldn't delete #{@dog.name}."
    end
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :age, :breed, :owner_id)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_action :set_owner, only: [:show, :edit, :update, :destroy]

  # GET /owners
  # GET /owners.json
  def index
    @owners = Owner.all
  end

  # GET /owners/1
  # GET /owners/1.json
  def show
  end

  # GET /owners/new
  def new
    @owner = Owner.new
  end

  # GET /owners/1/edit
  def edit
  end

  # POST /owners
  # POST /owners.json
  def create
    @owner = Owner.new(owner_params)

    respond_to do |format|
      if @owner.save
        format.html { redirect_to @owner, notice: 'Owner was successfully created.' }
        format.json { render :show, status: :created, location: @owner }
      else
        format.html { render :new }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /owners/1
  # PATCH/PUT /owners/1.json
  def update
    respond_to do |format|
      if @owner.update(owner_params)
        format.html { redirect_to @owner, notice: 'Owner was successfully updated.' }
        format.json { render :show, status: :ok, location: @owner }
      else
        format.html { render :edit }
        format.json { render json: @owner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /owners/1
  # DELETE /owners/1.json
  def destroy
    @owner.destroy
    respond_to do |format|
      format.html { redirect_to owners_url, notice: 'Owner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_owner
      @owner = Owner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def owner_params
      params.require(:owner).permit(:name, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/dogs/_form.html.erb
<%= form_for @dog do |dog_fields| %>

  <%= dog_fields.label :name %>
  <%= dog_fields.text_field :name %><br>

  <%= dog_fields.label :breed %>
  <%= dog_fields.text_field :breed %><br>

  <%= dog_fields.label :age %>
  <%= dog_fields.number_field :age %><br>

  <%= dog_fields.label :owner_id %>
  <%= dog_fields.collection_select :owner_id, Owner.all, :id, :name %><br>

  <%= dog_fields.submit %>

<% end %>

app/views/dogs/edit.html.erb
<h1>Edit A Dog</h1>

<%= render 'form' %>

app/views/dogs/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<h1>My Dogs</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Owner</th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.id %></td>
        <td><%= dog.name %></td>
        <td><%= dog.breed %></td>
        <td><%= dog.age %></td>
        <td><%= dog.owner.try(:name) %></td>
        <td><%= link_to "Show", dog_path(dog) %></td>
        <td><%= link_to "Edit", edit_dog_path(dog) %></td>
        <td>
          <%= link_to "Delete",
                      dog,
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Add A New Dog", new_dog_path %>

app/views/dogs/new.html.erb
<h1>Add A New Dog</h1>

<%= render 'form' %>

app/views/dogs/show.html.erb
<!-- Name -->
<h1>Details for <%= @dog.name %></h1>

<!-- ID -->
<p>
  <strong>ID:</strong> <%= @dog.id %>
</p>

<!-- Breed -->
<p>
  <strong>Breed:</strong> <%= @dog.breed %>
</p>

<!-- Age -->
<p>
  <strong>Age:</strong> <%= @dog.age %>
</p>

<!-- Owner -->
<p>
  <strong>Owner:</strong> <%= @dog.owner %>
</p>

<!-- Date Added -->
<p>
  <strong>Date Added:</strong> <%= @dog.created_at.stamp('02/05/2017') %>
</p>

<%= link_to "See all the doggies", dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoggieDaycare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_for(owner) do |f| %>
  <% if owner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(owner.errors.count, "error") %> prohibited this owner from being saved:</h2>

      <ul>
      <% owner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/owners/edit.html.erb
<h1>Editing Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Show', @owner %> |
<%= link_to 'Back', owners_path %>

app/views/owners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Owners</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @owners.each do |owner| %>
      <tr>
        <td><%= owner.name %></td>
        <td><%= owner.phone %></td>
        <td><%= link_to 'Show', owner %></td>
        <td><%= link_to 'Edit', edit_owner_path(owner) %></td>
        <td><%= link_to 'Destroy', owner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Owner', new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>

<%= render 'form', owner: @owner %>

<%= link_to 'Back', owners_path %>

app/views/owners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @owner.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @owner.phone %>
</p>

<%= link_to 'Edit', edit_owner_path(@owner) %> |
<%= link_to 'Back', owners_path %>